// Backend-internal types re-exported from shared, plus backend-only types
export type {
  EntryKind,
  BaseEntry,
  SystemEntry,
  ThinkingEntry,
  TextEntry,
  ToolCallEntry,
  ToolResultEntry,
  UserMessageEntry,
  ResultEntry,
  ParsedEntry,
  AgentStatus,
  SessionMeta,
  ClientMessage,
  ServerMessage,
  GameState,
  GameEvent,
  TravelHistoryEntry,
  CargoItem,
  ShipState,
  PlayerState,
  ShipModule,
  SessionSummary,
  AutoResumeState,
  RuntimeSettings,
} from '@cc-spacemolt/shared';
export { MAX_GAME_EVENTS } from '@cc-spacemolt/shared';
